databases:
  - name: postgres
    ipAllowList: []
    plan: free # optional (defaults to starter)

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      # - key: RAILS_MASTER_KEY
      #   sync: false
  - type: redis
    name: redis
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction
